version: "3.9"
services:
  wine:
    image: toetje585/arch-wine-vnc:latest
    container_name: arch-wine-vnc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /path/to/application:/opt/application
    ports:
      - 5900:5900
    restart: unless-stopped
