version: "3.9"
services:
  arch-wine-vnc:
    image: toetje585/arch-wine-vnc:latest
    container_name: arch-wine-vnc
    environment:
      - VNC_PASSWORD=winevnc
      - PUID=<UID from user>
      - PGID=<GID from user>
    volumes:
      - /path/to/applicationname:/opt/applicationname
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5900:5900/tcp
