- name: Dockerhub Readme Sync
  uses: ms-jpq/sync-dockerhub-readme@v1
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_WINE_ARCH_VNC }}
    readme: "./README.md"
    repository: toetje585/arch-wine-vnc
