name: Docker readme sync to dockerhub
- name: Sync
  uses: ms-jpq/sync-dockerhub-readme@v1
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_WINE_ARCH_VNC }}
    repository: toetje585/arch-wine-vnc
    readme: "./README.md"
